### ISSUE TITLE
Ignore specified embedded fields when generating an interface

### ISSUE THREAD

**Issue by hgl** [rjeczalik/interfaces#16]
Would you accept a PR that allows specifying ignored embedded fields?

My use case:

```
type DB struct {
  *underlyingDB.Client
}

func (db *DB) CreateUser() {}
```

I'd like to exclude methods from `underlyingDB.Client`.

do you think `-ignore Field1,Field2` would be a good argument format?

**Comment by hgl** [comment]
Hmm, looks like this is not easy to implement performatively.

I initially thought listing the field names after `if !field.Anonymous()` should be enough, but it seems the external packages are still walked.

**Comment by rjeczalik** [comment]
I think it would be good addition
