### ISSUE TITLE
Marking comment should be formed "Code generated by xxx"

### ISSUE THREAD

**Issue by kyoh86** [rjeczalik/interfaces#17]
ref: https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L299-L304

Many of tools to generate go code are marking code with "Code generated by xxx".
It's de facto standard.

**Comment by kyoh86** [comment]
see also: https://golang.org/pkg/cmd/go/internal/generate/

> To convey to humans and machine tools that code is generated,
> generated source should have a line that matches the following
> regular expression (in Go syntax):
> 
>    ^// Code generated .* DO NOT EDIT\.$
>
> The line may appear anywhere in the file, but is typically
> placed near the beginning so it is easy to find.

**Comment by kyoh86** [comment]
@rjeczalik how is this?

**Comment by rjeczalik** [comment]
@kyoh86 The interfacer puts the following comment at the beginning of each file:

```go
// Code generated by interfacer; DO NOT EDIT
```

**Comment by rjeczalik** [comment]
So it's there, closing the issue.

**Comment by kyoh86** [comment]
thanks!
