### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by decibel** [rjeczalik/interfaces#2]
I tried the normal `go get github.com/rjeczalik/interfaces` and it downloads but it doesn't install anything. A `go build` in `src/github.com/rjeczalik/interfaces` doesn't seem to do anything either.

**Comment by rjeczalik** [comment]
Hey @decibel, the main packages are in cmd/ directory - so you install with:

```
$ go get -u github.com/rjeczalik/interfaces/cmd/...
```
