### ISSUE TITLE
Marking comment should be formed "Code generated by xxx" in v0.1.0

### ISSUE THREAD

**Issue by kyoh86** [rjeczalik/interfaces#23]
Now `interfaces@latest` is v0.1.0.
But it marks comment "Created by...".

Put new tag please.

**Comment by rjeczalik** [comment]
Here you go - I drafted new release but it does not change much - https://github.com/rjeczalik/interfaces/releases/tag/v0.1.1.

> But it marks comment "Created by...".

I don't understand this comment, interfacer already preambles the generated files with proper comment:

```go
// Code generated by interfacer; DO NOT EDIT
```

https://github.com/rjeczalik/interfaces/blob/master/cmd/interfacer/main.go#L21

**Comment by kyoh86** [comment]
> I don't understand this comment, interfacer already preambles the generated files with proper comment:

On go module mode, `go get github.com/rjeczalik/interfaces/cmd/interfacer` installs latest release (on yesterday, it's v0.1.0).

**Comment by kyoh86** [comment]
thanks. resolved.
